version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
  db-migrator:
    build:
      context: ./aspnet-core
      dockerfile: ./Dockerfile.DbMigrator
    depends_on:
      - db
    environment:
      - ConnectionStrings:Default=Server=db;Port=5432;Database=tulumba;User ID=postgres;Password=example;
      - IdentityServer:Clients:Tulumba_App:RootUrl=http://localhost:8082
      - IdentityServer:Clients:Tulumba_Swagger:RootUrl=http://localhost:8083
  api:
    build:
      context: ./aspnet-core
      dockerfile: ./Dockerfile.Api
    depends_on:
      - db-migrator
    environment:
      - ConnectionStrings:Default=Server=db;Port=5432;Database=tulumba;User ID=postgres;Password=example;
      - AuthServer:Authority=http://localhost:8083
      - AuthServer:DisableRegistration=true
      - App:SelfUrl=http://localhost:8083
      - App:ClientUrl=http://localhost:8082
      - App:CorsOrigins=http://localhost:8082
      - App:RedirectAllowedUrls=http://localhost:8082
  app:
    build:
      context: ./angular
      dockerfile: ./Dockerfile
    depends_on:
      - api
    environment:
      - ANGULAR_CLIENT_URL_BASE=http://localhost:8082
      - API_HOST_URL_BASE=http://localhost:8083
  reverse_proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
      - 8083:8083
    links:
      - api
      - app
    environment:
      - API=api
      - APP=app