version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ~/Tulumba/postgres:/var/lib/postgresql/data
  db-migrator:
    build:
      context: ./aspnet-core
      dockerfile: ./Dockerfile.DbMigrator
    environment: 
      - ConnectionStrings:Default=Server=db;Port=5432;Database=tulumba;User ID=postgres;Password=example;
      #- IdentityServer:Clients:Tulumba_App:RootUrl=http://localhost:8082
      - IdentityServer:Clients:Tulumba_App:RootUrl=http://192.168.1.12
      #- IdentityServer:Clients:Tulumba_Swagger:RootUrl=http://localhost:8083
      - IdentityServer:Clients:Tulumba_Swagger:RootUrl=http://192.168.1.12:8083
    depends_on:
      - db
  api:
    build:
      context: ./aspnet-core
      dockerfile: ./Dockerfile.Api
    environment: 
      - ConnectionStrings:Default=Server=db;Port=5432;Database=tulumba;User ID=postgres;Password=example;
      #- AuthServer:Authority=http://localhost:8083
      - AuthServer:Authority=http://192.168.1.12:8083
      - AuthServer:DisableRegistration=true
      #- App:SelfUrl=http://localhost:8083
      - App:SelfUrl=http://192.168.1.12:8083
      #- App:ClientUrl=http://localhost:8082
      - App:ClientUrl=http://192.168.1.12
      #- App:CorsOrigins=http://localhost:8082,http://localhost:8083
      - App:CorsOrigins=http://192.168.1.12
      #- App:RedirectAllowedUrls=http://localhost:8082,http://localhost:8083
      - App:RedirectAllowedUrls=http://192.168.1.12
    depends_on:
      - db-migrator
  app:
    build:
      context: ./angular
      dockerfile: ./Dockerfile
    depends_on:
      - api
    environment:
      #- ANGULAR_CLIENT_URL_BASE=http://localhost:8082
      - ANGULAR_CLIENT_URL_BASE=http://192.168.1.12
      #- API_HOST_URL_BASE=http://localhost:8083
      - API_HOST_URL_BASE=http://192.168.1.12:8083
  reverse_proxy:
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 80:8082
        - 8083:8083   
      links:
        - api
        - app
      environment:
        - API=api
        - APP=app