version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ~/Tulumba/postgres:/var/lib/postgresql/data
  db-migrator:
    build:
      context: ./aspnet-core
      dockerfile: ./Dockerfile.DbMigrator
    environment:
      - ConnectionStrings:Default=Server=db;Port=5432;Database=tulumba;User ID=postgres;Password=example;
      - IdentityServer:Clients:Tulumba_App:RootUrl=http://tulumba2.ba
      - IdentityServer:Clients:Tulumba_Swagger:RootUrl=http://tulumba2.ba:8083
    depends_on:
      - db
  api:
    build:
      context: ./aspnet-core
      dockerfile: ./Dockerfile.Api
    depends_on:
      - db-migrator
    environment:
      - ConnectionStrings:Default=Server=db;Port=5432;Database=tulumba;User ID=postgres;Password=example;
      - AuthServer:Authority=http://tulumba2.ba:8083
      - AuthServer:DisableRegistration=true
      - App:SelfUrl=http://tulumba2.ba:8083
      - App:ClientUrl=http://tulumba2.ba
      - App:CorsOrigins=http://tulumba2.ba
      - App:RedirectAllowedUrls=http://tulumba2.ba
  app:
    build:
      context: ./angular
      dockerfile: ./Dockerfile
    depends_on:
      - api
    environment:
      - ANGULAR_CLIENT_URL_BASE=http://tulumba2.ba
      - API_HOST_URL_BASE=http://tulumba2.ba:8083
  reverse_proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      #- 80:8082  
      - 8083:8083
    links:
      - api
      - app
    environment:
      - API=api
      - APP=app