version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 127.0.0.1:5432:5432
    networks: 
      - bookkeepernet
  db-migrator:
    build:
      context: ./aspnet-core
      dockerfile: ./Dockerfile.DbMigrator
    environment: 
      - ConnectionStrings:Default=Server=db;Port=5432;Database=tulumba;User ID=postgres;Password=example;
      - IdentityServer:Clients:Tulumba_App:RootUrl=http://localhost:8082
      - IdentityServer:Clients:Tulumba_Swagger:RootUrl=http://localhost:8083
      
    networks:
      - bookkeepernet
    links:
      - db
    depends_on:
      - db
  api:
    build:
      context: ./aspnet-core
      dockerfile: ./Dockerfile.Api
    environment: 
      - ConnectionStrings:Default=Server=db;Port=5432;Database=tulumba;User ID=postgres;Password=example;
      - AuthServer:Authority=http://localhost:8083
      - App:SelfUrl=http://localhost:8083
      - App:ClientUrl=http://localhost:8082
      - App:CorsOrigins=http://localhost:8082,http://localhost:8083
      - App:RedirectAllowedUrls=http://localhost:8082,http://localhost:8083
#    ports:
#      - 127.0.0.1:44389:8083
    networks:
      - bookkeepernet
    links:
      - db
    depends_on:
      - db-migrator
  app:
    build:
      context: ./angular
      dockerfile: ./Dockerfile
#    ports:
#      - 127.0.0.1:8081:80
    networks:
      - bookkeepernet
    links:
      - api
    depends_on:
      - api
    environment:
      - ANGULAR_CLIENT_URL_BASE=http://localhost:8082
      - API_HOST_URL_BASE=http://localhost:8083
  reverse_proxy:
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 8082:8082
        - 8083:8083   
      links:
        - api
        - app
      networks:
        - bookkeepernet
      environment:
        - API=api
        - APP=app
networks:
  bookkeepernet:
    driver: bridge