name: Build App
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.18.1]

    steps:
      - uses: actions/checkout@v1

      - name: Node $
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: npm install and npm run build
        working-directory: ./angular/
        run: |          
          npm install --global yarn
          yarn install
          yarn build:prod
